#ifndef BOOKLOGPARAMETERS_HPP
#define BOOKLOGPARAMETERS_HPP

// Macros Name Parameters
#define BOOK_LOG_PARAMETERS_BOOK_LOG_USER_PESEL ("pesel")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_USER_FIRST_NAME ("firstName")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_USER_SURNAME ("surname")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_USER_PERMISSIONS ("permissions")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_ACTION ("action")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_ACTION_DATE_TIME ("actionDateTime")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_BOOK_ID ("bookId")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_DATE_TIME_OPTIONAL ("dateTime")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_USER_ID_COMMENT ("userIdCom")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_COMMENT_CONTENT ("comContent")
#define BOOK_LOG_PARAMETERS_BOOK_LOG_END_TOKEN ("end")

enum BookLogParameters{
    BOOK_LOG_USER_PESEL,   // Default Values
    BOOK_LOG_USER_FIRST_NAME,
    BOOK_LOG_USER_SURNAME,
    BOOK_LOG_USER_PERMISSIONS,
    BOOK_LOG_ACTION,
    BOOK_LOG_ACTION_DATE_TIME,   // End of Default
    BOOK_LOG_BOOK_ID,
    BOOK_LOG_DATE_TIME_OPTIONAL,
    BOOK_LOG_USER_ID_COMMENT,
    BOOK_LOG_COMMENT_CONTENT,
    BOOK_LOG_END_PARAMETER_TOKEN,   // Use to catch end of book read
    BOOK_LOG_NUMB_OF_PARAMETERS     // Use to catch errors
};


#endif // BOOKLOGPARAMETERS_HPP
