#ifndef BOOKLOGACTION_HPP
#define BOOKLOGACTION_HPP

enum BookLogAction{
    BOOK_LOG_ACTION_LOGIN,
    BOOK_LOG_ACTION_ADD_USER,
    BOOK_LOG_ACTION_REGISTER_USER,
    BOOK_LOG_ACTION_REMOVE_USER,
    BOOK_LOG_ACTION_LOGOUT,    
    BOOK_LOG_ACTION_ADD_BOOK,
    BOOK_LOG_ACTION_RESERVE_BOOK,
    BOOK_LOG_ACTION_CHECK_OUT_BOOK,
    BOOK_LOG_ACTION_EXPIRED_BOOK,
    BOOK_LOG_ACTION_RETURN_BOOK,
    BOOK_LOG_ACTION_REMOVE_BOOK,
    BOOK_LOG_ACTION_ADD_EDIT_COMMENT,
    BOOK_LOG_ACTION_REMOVE_COMMENT,
    NUMB_OF_BOOK_LOG_ACTIONS
};

#endif // BOOKLOGACTION_HPP
