#ifndef BOOKTYPE_HPP
#define BOOKTYPE_HPP

enum BookType{
    BOOK_AUTOBIOGRAPHY,
    BOOK_BIOGRAPHY,
    BOOK_DICTIONARY,
    BOOK_ENCYCLOPEDIA,
    BOOK_HISTORY,
    BOOK_JOURNAL,
    BOOK_GUIDE,
    BOOK_SCIENCE,
    BOOK_CRIME,
    BOOK_ROMANCE,
    BOOK_SCIENCE_FICTION,
    BOOK_DRAMA,
    BOOK_FAIRY_TALE,
    BOOK_FANTASY,
    BOOK_POETRY,
    BOOK_SATIR,
    BOOK_COMIC_BOOK,
    BOOK_HORROR,
    BOOK_THRILLER,
    BOOK_CHILDREN_LITERATURE,
    NUMB_OF_BOOK_TYPES
};

#endif // BOOKTYPE_HPP
