#ifndef BOOKSTATUS_HPP
#define BOOKSTATUS_HPP

enum BookStatus{
    BOOK_STATUS_FREE,
    BOOK_STATUS_RESERVED,
    BOOK_STATUS_CHECKED_OUT,
    BOOK_STATUS_EXPIRED,
    NUMB_OF_BOOK_STATUS
};

#endif // BOOKSTATUS_HPP
