#ifndef COMMANDTYPE_HPP
#define COMMANDTYPE_HPP

enum CommandType{
    COMMAND_TYPE_CLIENT_ADD,
    COMMAND_TYPE_CLIENT_REMOVE,
    COMMAND_TYPE_NUMB_OF_COMMANDS
};

#endif // COMMANDTYPE_HPP
