#ifndef COMMANDTYPE_HPP
#define COMMANDTYPE_HPP

#define COMMAND_TYPE_CLIENT_LOGIN_TEXT ("client/login")
#define COMMAND_TYPE_CLIENT_REGISTER_TEXT ("client/register")
#define COMMAND_TYPE_CLIENT_ADD_TEXT ("client/add")
#define COMMAND_TYPE_CLIENT_EDIT_TEXT ("client/edit")
#define COMMAND_TYPE_CLIENT_READ_TEXT ("client/read")
#define COMMAND_TYPE_CLIENT_REMOVE_TEXT ("client/remove")
#define COMMAND_TYPE_CLIENT_LOGOUT_TEXT ("client/logout")
#define COMMAND_TYPE_BOOK_ADD_TEXT ("book/add")
#define COMMAND_TYPE_BOOK_EDIT_TEXT ("book/edit")
#define COMMAND_TYPE_BOOK_READ_TEXT ("book/read")
#define COMMAND_TYPE_BOOK_REMOVE_TEXT ("book/remove")
#define COMMAND_TYPE_BOOK_RESERVE_TEXT ("book/reserve")
#define COMMAND_TYPE_BOOK_CHECK_OUT_TEXT ("book/checkout")
#define COMMAND_TYPE_BOOK_RETURN_TEXT ("book/return")
#define COMMAND_TYPE_BOOK_COMMENT_ADD_EDIT_TEXT ("book/comAddEdit")
#define COMMAND_TYPE_BOOK_COMMENT_REMOVE_TEXT ("book/comRemove")
#define COMMAND_TYPE_BOOK_LOG_READ_TEXT ("bookLog/read")
#define COMMAND_TYPE_CLIENT_ACTIVITY_TEXT ("client/activity")

enum CommandType{
    COMMAND_TYPE_CLIENT_ACTIVITY,
    COMMAND_TYPE_CLIENT_LOGIN,
    COMMAND_TYPE_CLIENT_LOGOUT,
    COMMAND_TYPE_CLIENT_REGISTER,
    COMMAND_TYPE_CLIENT_ADD,
    COMMAND_TYPE_CLIENT_EDIT,
    COMMAND_TYPE_CLIENT_READ,
    COMMAND_TYPE_CLIENT_REMOVE,
    COMMAND_TYPE_BOOK_ADD,
    COMMAND_TYPE_BOOK_EDIT,
    COMMAND_TYPE_BOOK_READ,
    COMMAND_TYPE_BOOK_REMOVE,
    COMMAND_TYPE_BOOK_RESERVE,
    COMMAND_TYPE_BOOK_CHECKOUT,
    COMMAND_TYPE_BOOK_RETURN,
    COMMAND_TYPE_BOOK_COMMENT_ADD_EDIT,
    COMMAND_TYPE_BOOK_COMMENT_REMOVE,
    COMMAND_TYPE_BOOK_LOG_READ,
    COMMAND_TYPE_NUMB_OF_COMMANDS
};

#endif // COMMANDTYPE_HPP
