#ifndef COMMANDTYPE_HPP
#define COMMANDTYPE_HPP

#define COMMAND_TYPE_CLIENT_LOGIN_TEXT ("client/login")
#define COMMAND_TYPE_CLIENT_REGISTER_TEXT ("client/register")
#define COMMAND_TYPE_CLIENT_ADD_TEXT ("client/add")
#define COMMAND_TYPE_CLIENT_EDIT_TEXT ("client/edit")
#define COMMAND_TYPE_CLIENT_READ_TEXT ("client/read")
#define COMMAND_TYPE_CLIENT_REMOVE_TEXT ("client/remove")

enum CommandType{
    COMMAND_TYPE_INIT_CLIENT_FILE, // PRIVATE SERVER COMMAND
    COMMAND_TYPE_INIT_BOOK_FILE, // PRIVATE SERVER COMMAND
    COMMAND_TYPE_CLIENT_LOGIN,
    COMMAND_TYPE_CLIENT_REGISTER,
    COMMAND_TYPE_CLIENT_ADD,
    COMMAND_TYPE_CLIENT_EDIT,
    COMMAND_TYPE_CLIENT_READ,
    COMMAND_TYPE_CLIENT_REMOVE,
    COMMAND_TYPE_BOOK_ADD,
    COMMAND_TYPE_BOOK_EDIT,
    COMMAND_TYPE_BOOK_READ,
    COMMAND_TYPE_BOOK_REMOVE,
    COMMAND_TYPE_NUMB_OF_COMMANDS
};

#endif // COMMANDTYPE_HPP
