#ifndef FILEREADINGSTATENUM_HPP
#define FILEREADINGSTATENUM_HPP

enum FileReadingStat{
    FILE_READING_SEARCHING,
    FILE_READING_READING_PARAM_NAME,
    FILE_READING_READING_VALUE
};

#endif // FILEREADINGSTATENUM_HPP
