#ifndef FILETYPEENUM_HPP
#define FILETYPEENUM_HPP

enum FileType{
    FILE_TYPE_CLIENTS_FILE,
    FILE_TYPE_BOOKS_FILE,
    FILE_TYPE_BOOK_LOG_FILE,
    NUMB_OF_FILE_TYPES
};

#endif // FILETYPEENUM_HPP
