#ifndef MESSAGETYPE_HPP
#define MESSAGETYPE_HPP

#define MESSAGE_TYPE_GET_TEXT ("GET")
#define MESSAGE_TYPE_POST_TEXT ("POST")

enum MessageType{
  POST,
  GET,
  NUMB_OF_MESSAGE_TYPES
};

#endif // MESSAGETYPE_HPP
