#ifndef READFILERULESTYPEENUM_HPP
#define READFILERULESTYPEENUM_HPP


enum ReadFileRulesType{
    READ_FILE_RULE_SINGLE_READ,
    READ_FILE_RULE_MULTI_READ
};

#endif // READFILERULESTYPEENUM_HPP
