#ifndef REQUESTDECODESTAT_HPP
#define REQUESTDECODESTAT_HPP

#define REQUEST_DECODE_CONTENT_TYPE_TEXT ("Content-Type")
#define REQUEST_DECODE_CONTENT_TYPE_VALUE_JSON_TEXT ("application/json")

enum RequestDecodeStat{
    GET_POST_READ,
    COMMAND_READ,
    CONTENT_TYPE_READ,
    DATA_READ,
    DECODING_FINISH
};

#endif // REQUESTDECODESTAT_HPP
