#ifndef RETURNERRORTYPE_HPP
#define RETURNERRORTYPE_HPP

#define RETURN_ERROR_JSON_VARIABLE_TEXT ("error")
#define RETURN_ERROR_JSON_PARSE_ERROR_VARIABLE_TEXT ("jsonParseError")

enum ReturnErrorType{
    RETURN_ERROR_WRONG_MESSAGE_TYPE,
    RETURN_ERROR_WRONG_COMMAND,
    RETURN_ERROR_NO_CONTENT_TYPE,
    RETURN_ERROR_CONTENT_TYPE_VALUE_NOT_JSON,
    RETURN_ERROR_NOT_COMPLETE_DATA,
    RETURN_ERROR_NOT_COMPLETE_HTTP_MSG,
    RETURN_ERROR_JSON_PARSE_ERROR,
    RETURN_ERROR_JSON_USER_NOT_SENT,
    RETURN_ERROR_JSON_BOOK_NOT_SENT,
    RETURN_ERROR_READ_FILES_RULES_JSON_CORRUPTED,
    RETURN_ERROR_BOOK_NOT_FOUND,
    RETURN_ERROR_USER_NOT_FOUND,
    RETURN_ERROR_FILE_NOT_REMOVED,
    RETURN_ERROR_USER_JSON_CORRUPTED,
    RETURN_ERROR_BOOK_JSON_CORRUPTED,
    RETURN_ERROR_WRONG_PASSWORD,
    RETURN_ERROR_USER_FOUND,
    RETURN_ERROR_BOOK_FOUND,
    RETURN_ERROR_FILE_ERROR,
    RETURN_ERROR_NO_ERROR
};

#endif // RETURNERRORTYPE_HPP
