#ifndef RETURNERRORTYPE_HPP
#define RETURNERRORTYPE_HPP

#define RETURN_ERROR_JSON_VARIABLE_TEXT ("error")
#define RETURN_ERROR_JSON_PARSE_ERROR_VARIABLE_TEXT ("jsonParseError")


enum ReturnErrorType{
    RETURN_ERROR_WRONG_MESSAGE_TYPE,
    RETURN_ERROR_WRONG_COMMAND,
    RETURN_ERROR_NO_CONTENT_TYPE,
    RETURN_ERROR_CONTENT_TYPE_VALUE_NOT_JSON,
    RETURN_ERROR_NOT_COMPLETE_DATA,
    RETURN_ERROR_NOT_COMPLETE_HTTP_MSG,
    RETURN_ERROR_JSON_PARSE_ERROR,
    RETURN_ERROR_NO_ERROR
};

#endif // RETURNERRORTYPE_HPP
