#ifndef USERPERMISSIONS_HPP
#define USERPERMISSIONS_HPP

enum UserPermissions{
    USER_PERMISSIONS_READER,
    USER_PERMISSIONS_LIBRARIAN,
    USER_PERMISSIONS_ADMIN,
    NUMB_OF_USER_PERMISSIONS
};

#endif // USERPERMISSIONS_HPP
